package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        expect {
            password("filebrowser.api.key", "credentialsJSON:a25a4bd9-18c8-4ed8-87ce-4c12970ffb25")
        }
        update {
            password("filebrowser.api.key", "credentialsJSON:253bb83e-c3ba-4fb1-a712-2062d9c25331")
        }
    }
}
