package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        add {
            checkbox("skip.tests", "true", label = "Skip Tests",
                      checked = "true", unchecked = "false")
        }
        add {
            checkbox("skip.diagrams", "false", label = "Skip Diagrams Generation",
                      checked = "true", unchecked = "false")
        }
    }
}
