if(EXTEND_WITH_PATTERN_BUILDER)
    add_subdirectory(pattern-builder)
    list(APPEND CLO3D_UI_DIRS ${PATTERN_BUILDER_EXTENSION_UI_DIR})
    list(APPEND CLO3D_SOURCES ${PATTERN_BUILDER_EXTENSION_SOURCES})
    list(APPEND CLO3D_INCLUDE_DIRS ${PATTERN_BUILDER_EXTENSION_INCLUDE_DIR})
endif ()
if (EXTEND_WITH_AUTHENTICATOR)
    add_subdirectory(authenticator)
    list(APPEND CLO3D_SOURCES ${AUTHENTICATOR_EXTENSION_SOURCES})
    list(APPEND CLO3D_INCLUDE_DIRS ${AUTHENTICATOR_EXTENSION_INCLUDE_DIR})
endif ()
if(EXTEND_WITH_DEV_TOOLS)
    add_subdirectory(dev-tools)
    list(APPEND CLO3D_UI_DIRS ${DEV_TOOLS_EXTENSION_UI_DIR})
    list(APPEND CLO3D_SOURCES ${DEV_TOOLS_EXTENSION_SOURCES})
    list(APPEND CLO3D_INCLUDE_DIRS ${DEV_TOOLS_EXTENSION_INCLUDE_DIR})
endif ()
set(CLO3D_UI_DIRS ${CLO3D_UI_DIRS} PARENT_SCOPE)
set(CLO3D_SOURCES ${CLO3D_SOURCES} PARENT_SCOPE)
set(CLO3D_INCLUDE_DIRS ${CLO3D_INCLUDE_DIRS} PARENT_SCOPE)