file(GLOB_RECURSE HOOKS_SOURCES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/*)
add_library(HooksLibrary STATIC ${HOOKS_SOURCES})
target_include_directories(HooksLibrary PUBLIC include)
if(WIN32)
    find_package(polyhook2 REQUIRED)
    target_link_libraries(HooksLibrary PUBLIC LoggingLibrary polyhook2::polyhook2)
else ()
    add_subdirectory(linux)
    target_link_libraries(HooksLibrary PUBLIC PolyhookStubs)
endif()