add_subdirectory(test)
file(GLOB_RECURSE DEV_TOOLS_EXTENSION_SOURCES CONFIGURE_DEPENDS
        ${CMAKE_CURRENT_SOURCE_DIR}/src/*
        ${CMAKE_CURRENT_SOURCE_DIR}/include/*
)
set(DEV_TOOLS_EXTENSION_SOURCES ${DEV_TOOLS_EXTENSION_SOURCES} PARENT_SCOPE)
set(DEV_TOOLS_EXTENSION_UI_DIR ${CMAKE_CURRENT_SOURCE_DIR}/ui PARENT_SCOPE)
set(DEV_TOOLS_EXTENSION_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/include PARENT_SCOPE)