@startuml
class "UI::BaseExtensionSettingsWidget" as C_0010218074716017551262
class C_0010218074716017551262 {
+BaseExtensionSettingsWidget(BaseExtensionSettings * extensionSettings, QWidget * parent) : void
..
+getBaseExtensionSettings() const : BaseExtensionSettings *
+read() : void
+write() : void
__
-extensionSettings_ : BaseExtensionSettings *
}
class "UI::ExtensionsSettingsDialog" as C_0002933765265782475360
class C_0002933765265782475360 {
+ExtensionsSettingsDialog(ExtensionsSettings * settings, QWidget * parent = nullptr) : void
+~ExtensionsSettingsDialog() : void
..
+accept() : void
+addPage(BaseExtensionSettingsWidget * page) const : void
+exec() : int
-processPages(void (BaseExtensionSettingsWidget::*)() processor) const : void
+reject() : void
+reset() : void
__
-extensionsSettings : ExtensionsSettings *
-ui : Ui::ExtensionsSettingsDialog *
}
abstract "UI::BaseUIExporterOptionsWidget" as C_0014335928297626608881
abstract C_0014335928297626608881 {
#BaseUIExporterOptionsWidget(QWidget * parent = nullptr) : void
..
{abstract} +getBaseUIExporterSettings() = 0 : BaseUIExporterSettingsBlockContainerWidget *
{abstract} +getOptions() = 0 : BaseUIExporterOptions *
+getTitle() : QString
+read() : void
{abstract} +setOptions(BaseUIExporterOptions * options) = 0 : void
+write() : void
__
}
class "UI::UIExporterToolSettingsWidget" as C_0014469424477386747179
class C_0014469424477386747179 {
+UIExporterToolSettingsWidget(UIExporterToolSettings * tool, QWidget * parent = nullptr) : void
+~UIExporterToolSettingsWidget() : void
..
-processOptions(void (BaseUIExporterOptionsWidget::*)() processor) const : void
+read() : void
+write() : void
__
-settings_ : UIExporterToolSettings *
-ui : Ui::UIExporterToolSettingsWidget *
}
class "UI::JsonUIExporterOptionsWidget" as C_0001932425129801750660
class C_0001932425129801750660 {
+JsonUIExporterOptionsWidget(QWidget * parent = nullptr) : void
+~JsonUIExporterOptionsWidget() : void
..
+classNameChanged(const QString & className) const : void
+fileNameChanged(const QString & fileName) const : void
+getBaseUIExporterSettings() : BaseUIExporterSettingsBlockContainerWidget *
+getOptions() : BaseUIExporterOptions *
+objectNameChanged(const QString & objectName) const : void
+read() : void
+rootFolderChanged(const QString & rootFolder) const : void
+setOptions(BaseUIExporterOptions * options) : void
+write() : void
__
-options_ : JsonUIExporterOptions *
-ui : Ui::JsonUIExporterOptionsWidget *
}
class "UI::XmlUIExporterOptionsWidget" as C_0002926957725831650451
class C_0002926957725831650451 {
+XmlUIExporterOptionsWidget(QWidget * parent = nullptr) : void
+~XmlUIExporterOptionsWidget() : void
..
+classNameChanged(const QString & className) const : void
+fileNameChanged(const QString & fileName) const : void
+getBaseUIExporterSettings() : BaseUIExporterSettingsBlockContainerWidget *
+getOptions() : BaseUIExporterOptions *
+objectNameChanged(const QString & objectName) const : void
+read() : void
+rootFolderChanged(const QString & rootFolder) const : void
+setOptions(BaseUIExporterOptions * options) : void
+write() : void
__
-options_ : XmlUIExporterOptions *
-ui : Ui::XmlUIExporterOptionsWidget *
}
class "UI::GeneralUIExporterOptionsWidget" as C_0008226627381243229116
class C_0008226627381243229116 {
+GeneralUIExporterOptionsWidget(QWidget * parent = nullptr) : void
+~GeneralUIExporterOptionsWidget() : void
..
+classNameChanged(const QString & className) : void
+fileNameChanged(const QString & fileName) : void
+getBaseUIExporterSettings() : BaseUIExporterSettingsBlockContainerWidget *
+getOptions() : BaseUIExporterOptions *
+objectNameChanged(const QString & objectName) : void
+read() : void
+rootFolderChanged(const QString & rootFolder) : void
+setOptions(BaseUIExporterOptions * options) : void
+write() : void
__
-options_ : GeneralUIExporterOptions *
-ui : Ui::GeneralUIExporterOptionsWidget *
}
abstract "BaseExtensionSettings" as C_0016168181109205541512
abstract C_0016168181109205541512 {
#~BaseExtensionSettings() constexpr = default : void
..
{abstract} #read() = 0 : void
+readSettings() : void
-setSettings(QSettings * settings) : void
{abstract} #write() = 0 : void
+writeSettings() : void
__
#settings_ : QSettings *
}
abstract "BaseDevTool" as C_0011953255168798855977
abstract C_0011953255168798855977 {
#~BaseDevTool() constexpr = default : void
..
{abstract} +configureSettings(ExtensionsSettings * extensionsSettings) = 0 : void
{abstract} +configureSettingsUI(UI::ExtensionsSettingsDialog * extensionsSettingsDialog) = 0 : void
+startup() : void
__
}
class "BaseExtension" as C_0008116604999349224677
class C_0008116604999349224677 {
#~BaseExtension() constexpr = default : void
..
+configure(QWidget * widget) : void
+configureMenu(QMenu * extensionMenu) : void
+configureSettings(ExtensionsSettings * extensionsSettings) : void
+configureSettingsUI(UI::ExtensionsSettingsDialog * extensionsSettingsDialog) : void
+configureStatusBar(QWidget * parent) : void
+install() : void
+startup() : void
__
}
abstract "BaseNativeShortcutHandler" as C_0004963345860278034983
abstract C_0004963345860278034983 {
#BaseNativeShortcutHandler(const QKeySequence & shortcut) : void
#~BaseNativeShortcutHandler() : void
..
{static} +getEventHandler(int id) : BaseNativeShortcutHandler *
{abstract} +handle() = 0 : void
-registerShortcut() const : void
{static} +registerShortcuts() : void
+setShortcut(const QKeySequence & shortcut) : void
{static} +startListening() : void
{static} +stopListening() : void
__
#id_ : int
#shortcut_ : QKeySequence
}
class "BaseUIExporterOptions" as C_0002364118592477390475
class C_0002364118592477390475 {
#~BaseUIExporterOptions() = default : void
..
+getClassName() const : QString
+getFileName() const : QString
+getObjectName() const : QString
+getRootFolder() const : QDir
+isEnabled() : bool
+read(const QSettings * settings) : void
+setClassName(const QString & className) : void
+setFileName(const QString & fileName) : void
+setObjectName(const QString & objectName) : void
+setRootFolder(const QDir & rootFolder) : void
+write(QSettings * settings) : void
__
-className_ : QString
-fileName_ : QString
-objectName_ : QString
-rootFolder_ : QDir
}
class "BaseUIExporterOptions::Keys" as C_0008405219056795622625
class C_0008405219056795622625 {
__
{static} +CLASS_NAME : const QString
{static} +FILE_NAME : const QString
{static} +OBJECT_NAME : const QString
{static} +ROOT_FOLDER : const QString
}
class "BaseUIExporterOptions::Defaults" as C_0007653554705407741843
class C_0007653554705407741843 {
__
{static} +CLASS_NAME : const QString
{static} +FILE_NAME : const QString
{static} +OBJECT_NAME : const QString
{static} +ROOT_FOLDER : const QDir
}
abstract "BaseUIExporter" as C_0010892009232951994255
abstract C_0010892009232951994255 {
#~BaseUIExporter() constexpr = default : void
..
+exportUI() : void
+exportUI(QWidget * widget) : void
{abstract} +exportUI(std::forward_list<QWidget *> widgets) = 0 : void
{abstract} +getOptions() = 0 : BaseUIExporterOptions *
__
}
class "GeneralUIExporterOptions" as C_0011694668836325593514
class C_0011694668836325593514 {
+getPickMyMouse() const : bool
+getShortcut() const : QKeySequence
+read(const QSettings * settings) : void
+setPickMyMouse(bool pickByMouse) : void
+setShortcut(const QKeySequence & shortcut) : void
+setShortcutHandler(BaseNativeShortcutHandler * shortcutHandler) : void
+write(QSettings * settings) : void
__
-pickByMouse_ : bool
-shortcutHandler_ : BaseNativeShortcutHandler *
-shortcut_ : QKeySequence
}
class "GeneralUIExporterOptions::Keys" as C_0015818025480861924188
class C_0015818025480861924188 {
__
{static} +PICK_BY_MOUSE : const QString
{static} +SHORTCUT : const QString
}
class "GeneralUIExporterOptions::Defaults" as C_0000253504876278353170
class C_0000253504876278353170 {
__
{static} +PICK_BY_MOUSE : const bool
{static} +SHORTCUT : const QKeySequence
}
class "UIExporterToolSettings" as C_0009062172491150368489
class C_0009062172491150368489 {
+addOptions(BaseUIExporterOptions * options) : void
+begin() const : std::_List_const_iterator<BaseUIExporterOptions *>::const_iterator
+end() const : std::_List_const_iterator<BaseUIExporterOptions *>::const_iterator
+read() : void
+write() : void
__
-options_ : std::list<BaseUIExporterOptions *>
}
class "UIExporterTool" as C_0010385705416594480772
class C_0010385705416594480772 {
+UIExporterTool(UIExporterToolSettings * uiExporterToolSettings, GeneralUIExporterOptions * options) : void
+~UIExporterTool() : void
..
+addExporter(BaseUIExporter * exporter) : void
+configureSettings(ExtensionsSettings * extensionsSettings) : void
+configureSettingsUI(UI::ExtensionsSettingsDialog * extensionsSettingsDialog) : void
+handle() : void
__
-exporters_ : std::forward_list<BaseUIExporter *>
-options_ : GeneralUIExporterOptions *
-uiExporterToolSettings_ : UIExporterToolSettings *
}
class "DevToolsExtension" as C_0010143777606507426232
class C_0010143777606507426232 {
+~DevToolsExtension() : void
..
+addDevTool(BaseDevTool * tool) : void
+configureSettings(ExtensionsSettings * extensionsSettings) : void
+configureSettingsUI(UI::ExtensionsSettingsDialog * extensionsSettingsDialog) : void
+startup() : void
__
-devTools_ : std::list<BaseDevTool *>
}
class "ExtensionsSettings" as C_0010078071459042722134
class C_0010078071459042722134 {
+ExtensionsSettings(const QString & organization, const QString & application) : void
+~ExtensionsSettings() : void
..
+addSettings(BaseExtensionSettings * settings) : void
+clear() const : void
+read() const : void
__
-extensionsSettings_ : std::forward_list<BaseExtensionSettings *>
-settings_ : QSettings *
}
class "JsonUIExporterOptions" as C_0003483514578000412706
class C_0003483514578000412706 {
+getIgnoreCSS() const : bool
+getVisibleOnly() const : bool
+isEnabled() : bool
+read(const QSettings * settings) : void
+setIgnoreCSS(bool ignoreCSS) : void
+setIsEnabled(bool isEnabled) : void
+setVisibleOnly(bool visibleOnly) : void
+write(QSettings * settings) : void
__
-ignoreCSS_ : bool
-isEnabled_ : bool
-visibleOnly_ : bool
}
class "JsonUIExporterOptions::Keys" as C_0003874668667896401620
class C_0003874668667896401620 {
__
{static} +IGNORE_CSS : const QString
{static} +IS_ENABLED : const QString
{static} +VISIBLE_ONLY : const QString
}
class "JsonUIExporterOptions::Defaults" as C_0014162813912439682906
class C_0014162813912439682906 {
__
{static} +IGNORE_CSS : const bool
{static} +IS_ENABLED : const bool
{static} +VISIBLE_ONLY : const bool
}
class "XmlUIExporterOptions" as C_0001751045535794520025
class C_0001751045535794520025 {
+getExportIcons() const : bool
+getUICompatible() const : bool
+isEnabled() : bool
+read(const QSettings * settings) : void
+setExportIcons(bool exportIcons) : void
+setIsEnabled(bool isEnabled) : void
+setUICompatible(bool uiCompatible) : void
+write(QSettings * settings) : void
__
-exportIcons_ : bool
-isEnabled_ : bool
-uiCompatible_ : bool
}
class "XmlUIExporterOptions::Keys" as C_0014832920068418374983
class C_0014832920068418374983 {
__
{static} +EXPORT_ICONS : const QString
{static} +IS_ENABLED : const QString
{static} +UI_COMPATIBLE : const QString
}
class "XmlUIExporterOptions::Defaults" as C_0006240226754342931017
class C_0006240226754342931017 {
__
{static} +EXPORT_ICONS : const bool
{static} +IS_ENABLED : const bool
{static} +UI_COMPATIBLE : const bool
}
class "ExtensionsManager" as C_0009727816568490413834
class C_0009727816568490413834 {
{static} +addExtension(BaseExtension * extension) : void
{static} +clearMessage() : void
{static} -install() : void
{static} -setMessage(const QString & message) : void
{static} +setMessage(const char * extensionName, const QString & message, bool logMessage = false) : void
__
{static} +action : QToolButton *
{static} -backgroundMessage_ : QLabel *
{static} +extensions : std::forward_list<BaseExtension *>
{static} +extensionsSettings : ExtensionsSettings *
{static} +mainWindow : QFrame *
}
class "XmlUIExporter" as C_0003462064165936373025
class C_0003462064165936373025 {
+XmlUIExporter(XmlUIExporterOptions * options) : void
+~XmlUIExporter() : void
..
+exportUI(std::forward_list<QWidget *> widgets) : void
+getOptions() : BaseUIExporterOptions *
__
-options_ : XmlUIExporterOptions *
}
class "JsonUIExporter" as C_0004682397984485573468
class C_0004682397984485573468 {
+JsonUIExporter(JsonUIExporterOptions * options) : void
+~JsonUIExporter() : void
..
+exportUI(std::forward_list<QWidget *> widgets) : void
{static} -getObjectJson(const QObject * object) : QJsonObject
+getOptions() : BaseUIExporterOptions *
-getWidgetJson(const QWidget * widget) : QJsonObject
__
-options_ : JsonUIExporterOptions *
}
C_0010218074716017551262 --> C_0016168181109205541512 : -extensionSettings_
C_0002933765265782475360 --> C_0010078071459042722134 : -extensionsSettings
C_0014469424477386747179 --> C_0009062172491150368489 : -settings_
C_0010218074716017551262 <|-- C_0014469424477386747179
C_0001932425129801750660 --> C_0003483514578000412706 : -options_
C_0014335928297626608881 <|-- C_0001932425129801750660
C_0002926957725831650451 --> C_0001751045535794520025 : -options_
C_0014335928297626608881 <|-- C_0002926957725831650451
C_0008226627381243229116 --> C_0011694668836325593514 : -options_
C_0014335928297626608881 <|-- C_0008226627381243229116
C_0016168181109205541512 <.. C_0010078071459042722134 : +<<friend>>
C_0011953255168798855977 <.. C_0010143777606507426232 : +<<friend>>
C_0008405219056795622625 --+ C_0002364118592477390475
C_0007653554705407741843 --+ C_0002364118592477390475
C_0011694668836325593514 --> C_0004963345860278034983 : -shortcutHandler_
C_0002364118592477390475 <|-- C_0011694668836325593514
C_0015818025480861924188 --+ C_0011694668836325593514
C_0000253504876278353170 --+ C_0011694668836325593514
C_0009062172491150368489 --> C_0002364118592477390475 : -options_
C_0016168181109205541512 <|-- C_0009062172491150368489
C_0010385705416594480772 --> C_0010892009232951994255 : -exporters_
C_0010385705416594480772 --> C_0011694668836325593514 : -options_
C_0010385705416594480772 --> C_0009062172491150368489 : -uiExporterToolSettings_
C_0011953255168798855977 <|-- C_0010385705416594480772
C_0004963345860278034983 <|-- C_0010385705416594480772
C_0010143777606507426232 --> C_0011953255168798855977 : -devTools_
C_0008116604999349224677 <|-- C_0010143777606507426232
C_0010078071459042722134 --> C_0016168181109205541512 : -extensionsSettings_
C_0002364118592477390475 <|-- C_0003483514578000412706
C_0003874668667896401620 --+ C_0003483514578000412706
C_0014162813912439682906 --+ C_0003483514578000412706
C_0002364118592477390475 <|-- C_0001751045535794520025
C_0014832920068418374983 --+ C_0001751045535794520025
C_0006240226754342931017 --+ C_0001751045535794520025
C_0009727816568490413834 --> C_0008116604999349224677 : +extensions
C_0009727816568490413834 --> C_0010078071459042722134 : +extensionsSettings
C_0009727816568490413834 <.. C_0008116604999349224677 : +<<friend>>
C_0003462064165936373025 --> C_0001751045535794520025 : -options_
C_0010892009232951994255 <|-- C_0003462064165936373025
C_0004682397984485573468 --> C_0003483514578000412706 : -options_
C_0010892009232951994255 <|-- C_0004682397984485573468
C_0002364118592477390475 -[hidden]down- C_0008405219056795622625
C_0002364118592477390475 -[hidden]down- C_0007653554705407741843
C_0011694668836325593514 -[hidden]down- C_0015818025480861924188
C_0011694668836325593514 -[hidden]down- C_0000253504876278353170
C_0003483514578000412706 -[hidden]down- C_0003874668667896401620
C_0003483514578000412706 -[hidden]down- C_0014162813912439682906
C_0001751045535794520025 -[hidden]down- C_0014832920068418374983
C_0001751045535794520025 -[hidden]down- C_0006240226754342931017
skinparam class {
  BackgroundColor #EAFAF1
  BorderColor #1E8449
  FontColor #0B5345
  AttributeFontColor #1E8449
  StereotypeFontColor #1E8449
  FontStyle Bold
}

skinparam class<<UI>> {
  BackgroundColor #F5EEF8
  BorderColor #8E44AD
  FontColor #4A235A
  AttributeFontColor #6C3483
  StereotypeFontColor #6C3483
}

skinparam class<<Base>> {
  BackgroundColor #F2F3F4
  BorderColor #2C3E50
  BorderThickness 3
  FontSize 16
  FontColor #2C3E50
  AttributeFontColor #566573
  StereotypeFontColor #808B96
  FontStyle Italic
}

skinparam class<<Extension>> {
  BackgroundColor #F9EBEA
  BorderColor #7B241C
  BorderThickness 3
  FontSize 16
  FontColor #7B241C
  AttributeFontColor #A93226
  StereotypeFontColor #CD6155
  FontStyle Italic
}


 class C_0016168181109205541512 <<Base>> 

 class C_0010218074716017551262 <<UI>> <<Base>> 

 class C_0002933765265782475360 <<UI>>  

 class C_0011953255168798855977 <<Base>> 

 class C_0008116604999349224677 <<Base>> 

 class C_0004963345860278034983 <<Base>> 

 class C_0002364118592477390475 <<Base>> 

 class C_0008405219056795622625 <<Base>> 

 class C_0007653554705407741843 <<Base>> 

 class C_0010892009232951994255 <<Base>> 

 

 

 

 

 

 class C_0010143777606507426232 <<Extension>> 

 class C_0014335928297626608881 <<UI>> <<Base>> 

 class C_0014469424477386747179 <<UI>>  

 

 

 

 

 class C_0001932425129801750660 <<UI>>  

 

 

 

 class C_0002926957725831650451 <<UI>>  

 

 

 class C_0008226627381243229116 <<UI>>  

 



'Generated with clang-uml, version 0.6.2
'LLVM version clang version 20.1.7 (https://github.com/llvm/llvm-project.git 6146a88f60492b520a36f8f8f3231e15f3cc6082)
@enduml
