@startuml
abstract "BaseCommandArguments" as C_0017826349404709606115
abstract C_0017826349404709606115 {
#BaseCommandArguments(QSettings * settings) : void
+~BaseCommandArguments() constexpr = default : void
..
{abstract} +getName() = 0 : QString
{abstract} #read() = 0 : void
+readSettings() : void
{abstract} #write() = 0 : void
+writeSettings() : void
__
#settings_ : QSettings *
}
class "UI::BaseCommandArgumentsWidget" as C_0008907065976657435877
class C_0008907065976657435877 {
+BaseCommandArgumentsWidget(BaseCommandArguments * arguments) : void
..
+load() : void
+save() const : void
__
#arguments_ : BaseCommandArguments *
}
class "UI::BaseDialog" as C_0010507882201943938998
class C_0010507882201943938998 {
+BaseDialog() : void
__
}
class "UI::CommandDialog" as C_0008115529870550764648
class C_0008115529870550764648 {
+CommandDialog(const QString & title, BaseCommandArgumentsWidget * argumentsWidget, BaseCommand * command) : void
+~CommandDialog() : void
..
+accept() : void
__
-argumentsWidget_ : BaseCommandArgumentsWidget *
-command_ : BaseCommand *
-ui : Ui::CommandDialog *
}
class "UI::NamedWidget" as C_0013765318333413517600
class C_0013765318333413517600 {
+NamedWidget(QWidget * parent) : void
+~NamedWidget() constexpr = default : void
..
+getTitle() const : QString
+setTitle(const QString & title) : void
+titleChanged(QString & title) : void
__
-title_ : QString
}
class "UI::BaseExtensionSettingsWidget" as C_0010218074716017551262
class C_0010218074716017551262 {
+BaseExtensionSettingsWidget(BaseExtensionSettings * extensionSettings, QWidget * parent) : void
..
+getBaseExtensionSettings() const : BaseExtensionSettings *
+read() : void
+write() : void
__
-extensionSettings_ : BaseExtensionSettings *
}
class "UI::ExtensionsSettingsDialog" as C_0002933765265782475360
class C_0002933765265782475360 {
+ExtensionsSettingsDialog(ExtensionsSettings * settings) : void
+~ExtensionsSettingsDialog() : void
..
+accept() : void
+addPage(BaseExtensionSettingsWidget * page) const : void
+exec() : int
-processPages(void (BaseExtensionSettingsWidget::*)() processor) const : void
+reject() : void
+reset() : void
__
-extensionsSettings : ExtensionsSettings *
-ui : Ui::ExtensionsSettingsDialog *
}
class "UI::ExportPatternCommandArgumentsWidget" as C_0018270316867500791566
class C_0018270316867500791566 {
+ExportPatternCommandArgumentsWidget(ExportPatternCommandArguments * arguments) : void
+~ExportPatternCommandArgumentsWidget() : void
..
+load() : void
+save() const : void
__
-ui : Ui::ExportPatternCommandArgumentsWidget *
}
abstract "BaseCommand" as C_0014850613953214503793
abstract C_0014850613953214503793 {
#BaseCommand(BaseCommandArguments * arguments) : void
+~BaseCommand() : void
..
{abstract} +run() = 0 : void
__
#arguments_ : BaseCommandArguments *
}
class "CommandRunner" as C_0011922452949065162588
class C_0011922452949065162588 {
+CommandRunner(QSettings * settings, QMenu * menu) : void
..
+add<Command,Arguments,Widget>() : void
__
-menu_ : QMenu *
-settings_ : QSettings *
}
abstract "BaseExtensionSettings" as C_0016168181109205541512
abstract C_0016168181109205541512 {
#~BaseExtensionSettings() constexpr = default : void
..
{abstract} #read() = 0 : void
+readSettings() : void
-setSettings(QSettings * settings) : void
{abstract} #write() = 0 : void
+writeSettings() : void
__
#settings_ : QSettings *
}
class "BaseExtension" as C_0008116604999349224677
class C_0008116604999349224677 {
#~BaseExtension() constexpr = default : void
..
+configure(QWidget * widget) : void
+configureCommands(CommandRunner * container) : void
+configureMenu(QMenu * extensionMenu) : void
+configureSettings(ExtensionsSettings * extensionsSettings) : void
+configureSettingsUI(UI::ExtensionsSettingsDialog * extensionsSettingsDialog) : void
+configureStatusBar(QWidget * parent) : void
+install() : void
+startup() : void
__
}
class "ExtensionsSettings" as C_0010078071459042722134
class C_0010078071459042722134 {
+ExtensionsSettings(QSettings * settings) : void
+~ExtensionsSettings() : void
..
+addSettings(BaseExtensionSettings * settings) : void
+clear() const : void
+read() const : void
__
-extensionsSettings_ : std::forward_list<BaseExtensionSettings *>
-settings_ : QSettings *
}
class "ExtensionsManager" as C_0009727816568490413834
class C_0009727816568490413834 {
{static} +addExtension(BaseExtension * extension) : void
{static} +clearMessage() : void
{static} -install() : void
{static} -setMessage(const QString & message) : void
{static} +setMessage(const char * extensionName, const QString & message, bool logMessage = false) : void
__
{static} +ROOT_EXTENSIONS_DIR : QDir
{static} +action : QToolButton *
{static} -backgroundMessage_ : QLabel *
{static} +commandRunner_ : CommandRunner *
{static} +extensions : std::forward_list<BaseExtension *>
{static} +extensionsSettings : ExtensionsSettings *
{static} +mainWindow : QFrame *
}
class "ExportPatternCommandArguments" as C_0006399459746480959036
class C_0006399459746480959036 {
+ExportPatternCommandArguments(QSettings * settings) : void
..
+getFilePath() const : const QString &
+getName() : QString
+read() : void
+setFilePath(const QString & filePath) : void
+write() : void
__
{static} +NAME : const char *const
-filePath_ : QString
}
class "ExportPatternCommandArguments::Keys" as C_0003721449402365497430
class C_0003721449402365497430 {
__
{static} +FILE_PATH : const char *const
}
class "ExportPatternCommandArguments::Defaults" as C_0015580118860542650828
class C_0015580118860542650828 {
__
{static} +FILE_PATH : QString
}
class "ExportPatternCommand" as C_0010281554756572473112
class C_0010281554756572473112 {
+ExportPatternCommand(ExportPatternCommandArguments * arguments) : void
..
+run() : void
__
}
C_0008907065976657435877 --> C_0017826349404709606115 : #arguments_
C_0008115529870550764648 *-- C_0014850613953214503793 : -command_
C_0008115529870550764648 *-- C_0008907065976657435877 : -argumentsWidget_
C_0010507882201943938998 <|-- C_0008115529870550764648
C_0010218074716017551262 --> C_0016168181109205541512 : -extensionSettings_
C_0013765318333413517600 <|-- C_0010218074716017551262
C_0002933765265782475360 --> C_0010078071459042722134 : -extensionsSettings
C_0010507882201943938998 <|-- C_0002933765265782475360
C_0008907065976657435877 <|-- C_0018270316867500791566
C_0014850613953214503793 --> C_0017826349404709606115 : #arguments_
C_0016168181109205541512 <.. C_0010078071459042722134 : +<<friend>>
C_0010078071459042722134 --> C_0016168181109205541512 : -extensionsSettings_
C_0009727816568490413834 --> C_0008116604999349224677 : +extensions
C_0009727816568490413834 --> C_0010078071459042722134 : +extensionsSettings
C_0009727816568490413834 --> C_0011922452949065162588 : +commandRunner_
C_0009727816568490413834 <.. C_0008116604999349224677 : +<<friend>>
C_0017826349404709606115 <|-- C_0006399459746480959036
C_0003721449402365497430 --+ C_0006399459746480959036
C_0015580118860542650828 --+ C_0006399459746480959036
C_0014850613953214503793 <|-- C_0010281554756572473112
skinparam class {
  BackgroundColor #EAFAF1
  BorderColor #1E8449
  FontColor #0B5345
  AttributeFontColor #1E8449
  StereotypeFontColor #1E8449
  FontStyle Bold
}

skinparam class<<UI>> {
  BackgroundColor #F5EEF8
  BorderColor #8E44AD
  FontColor #4A235A
  AttributeFontColor #6C3483
  StereotypeFontColor #6C3483
}

skinparam class<<Base>> {
  BackgroundColor #F2F3F4
  BorderColor #2C3E50
  BorderThickness 3
  FontSize 16
  FontColor #2C3E50
  AttributeFontColor #566573
  StereotypeFontColor #808B96
  FontStyle Italic
}

skinparam class<<Extension>> {
  BackgroundColor #F9EBEA
  BorderColor #7B241C
  BorderThickness 3
  FontSize 16
  FontColor #7B241C
  AttributeFontColor #A93226
  StereotypeFontColor #CD6155
  FontStyle Italic
}


 class C_0017826349404709606115 <<Base>> 

 class C_0008907065976657435877 <<UI>> <<Base>> 

 class C_0014850613953214503793 <<Base>> 

 class C_0010507882201943938998 <<UI>> <<Base>> 

 class C_0008115529870550764648 <<UI>>  

 

 class C_0013765318333413517600 <<UI>>  

 class C_0016168181109205541512 <<Base>> 

 class C_0010218074716017551262 <<UI>> <<Base>> 

 class C_0002933765265782475360 <<UI>>  

 class C_0008116604999349224677 <<Base>> 

 

 

 

 

 

 class C_0018270316867500791566 <<UI>>  

 


'Generated with clang-uml, version 0.6.2
'LLVM version clang version 20.1.7 (https://github.com/llvm/llvm-project.git 6146a88f60492b520a36f8f8f3231e15f3cc6082)
@enduml
