file(GLOB_RECURSE WIDGETS_HEADERS CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/include/*)
file(GLOB_RECURSE WIDGETS_SOURCES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/*)

add_library(Widgets STATIC ${WIDGETS_HEADERS} ${WIDGETS_SOURCES})
set_target_properties(Widgets PROPERTIES AUTOUIC_SEARCH_PATHS "${CMAKE_CURRENT_SOURCE_DIR}/ui")
target_include_directories(Widgets PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(Widgets PUBLIC Qt5::Widgets)