#ifndef FASHIONDESIGNAPPS_GENERALUIEXPORTEROPTIONS_H
#define FASHIONDESIGNAPPS_GENERALUIEXPORTEROPTIONS_H

#include "BaseUIExporterOptions.h"

class GeneralUIExporterOptions: public BaseUIExporterOptions {
};


#endif //FASHIONDESIGNAPPS_GENERALUIEXPORTEROPTIONS_H