@startuml
class "boost::optional<Project const*>" as C_0016954960473212819266
class C_0016954960473212819266 {
__
}
class "Chrysalis::NamedElementsContainer<Chrysalis::Parameter>" as C_0009799515597078618207
class C_0009799515597078618207 {
__
}
class "Chrysalis::ParametersModel" as C_0006294982762641672186
class C_0006294982762641672186 {
+columnCount(const QModelIndex & parent) const : int
+data(const QModelIndex & index, int role) const : QVariant
+flags(const QModelIndex & index) const : Qt::ItemFlags
+headerData(int section, Qt::Orientation orientation, int role) const : QVariant
+rowCount(const QModelIndex & parent) const : int
+setData(const QModelIndex & index, const QVariant & value, int role) : bool
+setParameters(ParametersContainer * parameters) : void
__
-parameters_ : ParametersContainer *
}
class "Chrysalis::ParametersElement" as C_0003994509085763311703
class C_0003994509085763311703 {
+getModel() const : ParametersModel *
+modelChanged() : void
+setModel(ParametersModel * model) : void
+setParameters(ParametersContainer * parameters) : void
__
-model_ : ParametersModel *
-parameters_ : ParametersContainer *
}
class "Chrysalis::ProjectElement" as C_0008929981772084998866
class C_0008929981772084998866 {
+ProjectElement(QQuickItem * parent = nullptr) : void
+~ProjectElement() : void
..
+closeProject() : void
+createProject() : void
+filePathChanged() : void
+getFilePath() const : QUrl
+getName() const : QString
+getParameters() const : ParametersElement *
+hasProject() const : bool
+nameChanged() : void
+openProject(const QUrl & filePath) : void
+parametersChanged() : void
+projectChanged(const Project * project) : void
+saveProject(const QUrl & filePath) : void
+setFilePath(const QUrl & filePath) : void
+setName(const QString & name) : void
+setParameters(ParametersElement * parameters) : void
__
-filePath_ : QUrl
-parameters_ : ParametersElement *
-project_ : Project *
}
class "Chrysalis::Area" as C_0017448836424981341256
class C_0017448836424981341256 {
+Area() : void
+Area(float x, float y, float width, float height) : void
..
+height() const : const float &
+offset(float deltaX, float deltaY) : void
+scale(float scaleFactor) : void
+setSize(float width, float height) : void
+width() const : const float &
+x() const : const float &
+y() const : const float &
__
-height_ : float
-width_ : float
-x_ : float
-y_ : float
}
class "Chrysalis::Vertex2f" as C_0014045523936343269615
class C_0014045523936343269615 {
+Vertex2f(float x, float y) : void
+Vertex2f(const Point & point) : void
..
{static} +layout() : std::vector<std::pair<int,void *>>
+move(const Point & point) : void
+x() const : const float &
+y() const : const float &
__
-x_ : float
-y_ : float
}
abstract "Chrysalis::BaseRendererData<V>" as C_0010648050014975774765
abstract C_0010648050014975774765 {
#BaseRendererData() = default : void
+~BaseRendererData() = default : void
..
+shouldUpload() : bool
{abstract} +size() = 0 : size_t
+updateVBO() : void
{abstract} +vbo() = 0 : std::vector<V>
__
-shouldUpload_ : bool
}
abstract "Chrysalis::BaseRenderer<D>" as C_0011449526761968468087
abstract C_0011449526761968468087 {
#BaseRenderer(D * data) : void
#~BaseRenderer() : void
..
{abstract} +draw() = 0 : void
+initialize() : void
+render() : void
+upload() : void
__
#data_ : D *
-vao_ : GLuint
-vbo_ : GLuint
}
class "Chrysalis::BaseRendererData<Chrysalis::Vertex2f>" as C_0003814330884215016651
class C_0003814330884215016651 {
__
}
class "Chrysalis::CartesianRendererData" as C_0011935714076265489658
class C_0011935714076265489658 {
+buildGrid(const Area & area, float gridSize) : void
+size() : size_t
+vbo() : std::vector<Vertex2f>
__
-data_ : std::vector<Vertex2f>
}
class "Chrysalis::BaseOpenGLProgram" as C_0009014904075807390969
class C_0009014904075807390969 {
#BaseOpenGLProgram(const char * vertexShader, const char * fragmentShader) : void
+~BaseOpenGLProgram() : void
..
+bind() const : void
+initialize() : void
{static} -prepareShader(const char * shaderCode, GLenum shaderType) : GLint
{static} +release() : void
#setUniformValue(const char * name, GLint value) const : void
#setUniformValue(const char * name, GLfloat value) const : void
#setUniformValue(const char * name, const glm::mat4x4 & value) const : void
#setUniformValue(const char * name, GLfloat x, GLfloat y, GLfloat z, GLfloat w) const : void
__
-fragmentShader_ : const char *
-program_ : GLint
-vertexShader_ : const char *
}
class "Chrysalis::MainOpenGLProgram" as C_0008404019008873523889
class C_0008404019008873523889 {
+MainOpenGLProgram() : void
..
+setColor(float r, float g, float b, float a) const : void
+setPointRadius(float radius) const : void
+setProjection(const glm::mat4x4 & projection) const : void
__
}
class "Chrysalis::BaseRenderer<Chrysalis::CartesianRendererData>" as C_0009985944204983126988
class C_0009985944204983126988 {
__
}
class "Chrysalis::CartesianRenderer" as C_0012069508297492912490
class C_0012069508297492912490 {
+CartesianRenderer(MainOpenGLProgram * program, CartesianRendererData * data) : void
..
+changeArea(const Area & area) const : void
+draw() : void
__
-gridSize_ : float
-program_ : MainOpenGLProgram *
}
class "Chrysalis::Vertex3f" as C_0014044642128017633618
class C_0014044642128017633618 {
+Vertex3f(const Point & point) : void
+Vertex3f(const Point & point, float attribute) : void
+Vertex3f(float x, float y) : void
+Vertex3f(float x, float y, float attribute) : void
..
+attribute(float value) : void
+attribute() const : const float &
{static} +layout() : std::vector<std::pair<int,void *>>
__
-attribute_ : float
}
class "Chrysalis::BaseRendererData<Chrysalis::Vertex3f>" as C_0003071611879058204012
class C_0003071611879058204012 {
__
}
class "Chrysalis::CursorRendererData" as C_0010368778014850136780
class C_0010368778014850136780 {
+projectCursor(float x, float y) : void
+size() : size_t
+vbo() : std::vector<Vertex3f>
__
-data_ : std::vector<Vertex3f>
}
abstract "Chrysalis::BaseAnimatedRenderer<D>" as C_0006005639932984129856
abstract C_0006005639932984129856 {
#BaseAnimatedRenderer(D * data) : void
..
+animate() : bool
#complete() : void
{abstract} #prepareNextFrame(int64_t startTime, int64_t previousFrameTime, int64_t currentFrameTime) = 0 : void
__
-isCompleted_ : bool
-startTime_ : int64_t
-time_ : int64_t
}
class "Chrysalis::BaseAnimatedRenderer<Chrysalis::CursorRendererData>" as C_0014979996669646431041
class C_0014979996669646431041 {
__
}
class "Chrysalis::CursorRenderer" as C_0014720307744216466084
class C_0014720307744216466084 {
+CursorRenderer(MainOpenGLProgram * program, CursorRendererData * data) : void
..
+displayCursor(float x, float y) : void
+draw() : void
+hideCursor() : void
#prepareNextFrame(int64_t startTime, int64_t previousFrameTime, int64_t currentFrameTime) : void
__
-displayCursor_ : bool
-opacity_ : float
-program_ : MainOpenGLProgram *
}
class "Chrysalis::PatternShapeRendererData" as C_0011694023645327839877
class C_0011694023645327839877 {
+size() : size_t
+vbo() : std::vector<Vertex2f>
__
}
class "Chrysalis::BaseRenderer<Chrysalis::PatternShapeRendererData>" as C_0015376512757975965057
class C_0015376512757975965057 {
__
}
class "Chrysalis::PatternShapeRenderer" as C_0015064054511240045445
class C_0015064054511240045445 {
+PatternShapeRenderer(PatternShapeRendererData * data) : void
..
+draw() : void
+scaleChanged(float scale) : void
__
}
class "Chrysalis::PatternSpaceRendererData" as C_0011260122464657857622
class C_0011260122464657857622 {
+arrowsSize() const : size_t
{static} -buildArrow(const CG::Point & pointFrom, const CG::Point & pointTo) : Arrow
{static} -intersectionPoint(const CG::Point & pointFrom, const CG::Point & pointTo) : CG::Point
{static} -length(const CG::Point & pointFrom, const CG::Point & pointTo) : float
+linesSize() const : size_t
+pointAdded(const Point * point) : void
+pointAtPosition(float x, float y) const : const Point *
+pointMoved(const Point * point) : void
+pointsSize() const : size_t
+relativePointConnectionAdded(const Point * from, const Point * to) : void
+relativePointConnectionRemoved(const Point * from, const Point * to) : void
+size() : size_t
+vbo() : std::vector<Vertex3f>
__
{static} +POINT_RADIUS : const float
-arrows_ : std::vector<Vertex3f>
-connectionsMapFrom_ : std::unordered_map<const Point *,std::unordered_map<const Point *,int>>
-connectionsMapTo_ : std::unordered_map<const Point *,std::unordered_map<const Point *,int>>
-lines_ : std::vector<Vertex3f>
-pointIndices_ : std::unordered_map<const Point *,int>
-points_ : std::vector<Vertex3f>
}
class "Chrysalis::PatternSpaceRendererData::Arrow" as C_0012563006101612362629
class C_0012563006101612362629 {
__
+baseBegin : CG::Point
+baseEnd : CG::Point
+leftWing : CG::Point
+rightWing : CG::Point
}
class "Chrysalis::BaseRenderer<Chrysalis::PatternSpaceRendererData>" as C_0000794775527725307768
class C_0000794775527725307768 {
__
}
class "Chrysalis::PatternSpaceRenderer" as C_0008349615279724093078
class C_0008349615279724093078 {
+PatternSpaceRenderer(MainOpenGLProgram * program, PatternSpaceRendererData * rendererData) : void
..
+draw() : void
+pointAtPosition(float x, float y) const : const Point *
+scaleChanged(float scale) : void
__
-pointRadius_ : float
-program_ : MainOpenGLProgram *
}
class "Chrysalis::PatternRenderer" as C_0010886489269060501830
class C_0010886489269060501830 {
+PatternRenderer(PatternSpaceRenderer * spaceRenderer, PatternShapeRenderer * shapeRenderer) : void
+~PatternRenderer() : void
..
+initialize() const : void
+render() const : void
+scaleChanged(float scale) const : void
+spaceRenderer() const : const PatternSpaceRenderer *
+upload() const : void
__
-shapeRenderer_ : PatternShapeRenderer *
-spaceRenderer_ : PatternSpaceRenderer *
}
class "Chrysalis::ProjectRenderer" as C_0014065787526185037529
class C_0014065787526185037529 {
+ProjectRenderer(MainOpenGLProgram * program, CartesianRenderer * cartesianRenderer, CursorRenderer * cursorRenderer) : void
+~ProjectRenderer() : void
..
+areaOffsetChanged(float deltaX, float deltaY) : void
+areaSizeChanged(float width, float height) : void
+cursorPositionChanged(float x, float y) const : void
+initialize() const : void
#prepareNextFrame() const : bool
#render() const : void
+scaleChanged(float scaleFactor, float zoomX, float zoomY) : void
-updateProjectionMatrix() : void
#useProject(const Project * project) : void
__
-area_ : Area
-cartesianRenderer_ : CartesianRenderer *
-cursorRenderer_ : CursorRenderer *
-isInitialized_ : bool
-patternRenderers_ : std::list<PatternRenderer>
-program_ : MainOpenGLProgram *
-projection_ : glm::mat4x4
-scale_ : float
}
class "Chrysalis::ProjectSceneElement" as C_0017487605234251182146
class C_0017487605234251182146 {
+ProjectSceneElement(QQuickItem * parent = nullptr) : void
..
+createRenderer() const : Renderer *
#hoverMoveEvent(QHoverEvent * event) : void
#mouseMoveEvent(QMouseEvent * event) : void
#mousePressEvent(QMouseEvent * event) : void
#mouseReleaseEvent(QMouseEvent * event) : void
-normalize(QPointF && point) const : QPointF
+projectChanged(const Project * project) : void
#wheelEvent(QWheelEvent * event) : void
__
-isLeftMouseButtonPressed_ : bool
-mousePosition_ : QPointF
-renderer_ : Renderer *
-windowPosition_ : QPointF
}
class "Chrysalis::ProjectSceneElement::Renderer" as C_0015644395940763327543
class C_0015644395940763327543 {
+Renderer(MainOpenGLProgram * program, CartesianRenderer * cartesianRenderer, CursorRenderer * cursorRenderer) : void
+changeProject(const Project * project) : void
#createFramebufferObject(const QSize & size) : QOpenGLFramebufferObject *
#render() : void
#synchronize(QQuickFramebufferObject *) : void
__
-pendingProject_ : boost::optional<const Project *>
}
class "CGAL::Point_2<Chrysalis::CG::LinearKernel>" as C_0003407114271749040649
class C_0003407114271749040649 {
__
}
class "glm::mat<4,4,float,defaultp>" as C_0011668248383743793436
class C_0011668248383743793436 {
__
}
C_0006294982762641672186 --> C_0009799515597078618207 : -parameters_
C_0003994509085763311703 --> C_0006294982762641672186 : -model_
C_0003994509085763311703 --> C_0009799515597078618207 : -parameters_
C_0008929981772084998866 --> C_0003994509085763311703 : -parameters_
C_0010648050014975774765 ..> C_0014045523936343269615
C_0003814330884215016651 ..|> C_0010648050014975774765
C_0011935714076265489658 o-- C_0014045523936343269615 : -data_
C_0003814330884215016651 <|-- C_0011935714076265489658
C_0009014904075807390969 <|-- C_0008404019008873523889
C_0009985944204983126988 ..|> C_0011449526761968468087
C_0012069508297492912490 --> C_0008404019008873523889 : -program_
C_0009985944204983126988 <|-- C_0012069508297492912490
C_0014045523936343269615 <|-- C_0014044642128017633618
C_0003071611879058204012 ..|> C_0010648050014975774765
C_0010368778014850136780 o-- C_0014044642128017633618 : -data_
C_0003071611879058204012 <|-- C_0010368778014850136780
C_0011449526761968468087 <|-- C_0006005639932984129856
C_0014979996669646431041 ..|> C_0006005639932984129856
C_0014720307744216466084 --> C_0008404019008873523889 : -program_
C_0014979996669646431041 <|-- C_0014720307744216466084
C_0003814330884215016651 <|-- C_0011694023645327839877
C_0015376512757975965057 ..|> C_0011449526761968468087
C_0015376512757975965057 <|-- C_0015064054511240045445
C_0011260122464657857622 o-- C_0014044642128017633618 : -lines_
C_0011260122464657857622 o-- C_0014044642128017633618 : -arrows_
C_0011260122464657857622 o-- C_0014044642128017633618 : -points_
C_0003071611879058204012 <|-- C_0011260122464657857622
C_0012563006101612362629 --+ C_0011260122464657857622
C_0012563006101612362629 o-- C_0003407114271749040649 : +baseBegin
C_0012563006101612362629 o-- C_0003407114271749040649 : +baseEnd
C_0012563006101612362629 o-- C_0003407114271749040649 : +leftWing
C_0012563006101612362629 o-- C_0003407114271749040649 : +rightWing
C_0000794775527725307768 ..|> C_0011449526761968468087
C_0008349615279724093078 --> C_0008404019008873523889 : -program_
C_0000794775527725307768 <|-- C_0008349615279724093078
C_0010886489269060501830 *-- C_0008349615279724093078 : -spaceRenderer_
C_0010886489269060501830 *-- C_0015064054511240045445 : -shapeRenderer_
C_0014065787526185037529 o-- C_0017448836424981341256 : -area_
C_0014065787526185037529 o-- C_0011668248383743793436 : -projection_
C_0014065787526185037529 *-- C_0008404019008873523889 : -program_
C_0014065787526185037529 *-- C_0014720307744216466084 : -cursorRenderer_
C_0014065787526185037529 *-- C_0012069508297492912490 : -cartesianRenderer_
C_0014065787526185037529 o-- C_0010886489269060501830 : -patternRenderers_
C_0017487605234251182146 --> C_0015644395940763327543 : -renderer_
C_0015644395940763327543 --+ C_0017487605234251182146
C_0015644395940763327543 o-- C_0016954960473212819266 : -pendingProject_
C_0014065787526185037529 <|-- C_0015644395940763327543
skinparam class {
  BackgroundColor #EAFAF1
  BorderColor #1E8449
  FontColor #0B5345
  AttributeFontColor #1E8449
  StereotypeFontColor #1E8449
  FontStyle Bold
}

skinparam class<<Base>> {
  BackgroundColor #F2F3F4
  BorderColor #2C3E50
  BorderThickness 3
  FontSize 16
  FontColor #2C3E50
  AttributeFontColor #566573
  StereotypeFontColor #808B96
  FontStyle Italic
}

skinparam class<<Element>> {
  BackgroundColor #EBF5FB
  BorderColor #1A5276
  FontColor #1A5276
  AttributeFontColor #2E86C1
  StereotypeFontColor #2E86C1
  FontStyle Bold
}

skinparam class<<Model>> {
  BackgroundColor #E8F8F5
  BorderColor #0E6655
  BorderThickness 3
  FontSize 16
  FontColor #0E6655
  AttributeFontColor #117A65
  StereotypeFontColor #148F77
  FontStyle Italic
}


   class C_0009799515597078618207 <<Element>>
  

   class C_0006294982762641672186 <<Model>>
  

   class C_0003994509085763311703 <<Element>>
  

   class C_0008929981772084998866 <<Element>>
  

  

  

   class C_0010648050014975774765 <<Base>>
  

   class C_0011449526761968468087 <<Base>>
  

   class C_0003814330884215016651 <<Base>>
  

  

  

   class C_0009014904075807390969 <<Base>>
  

  

   class C_0009985944204983126988 <<Base>>
  

  

  

   class C_0003071611879058204012 <<Base>>
  

  

   class C_0006005639932984129856 <<Base>>
  

   class C_0014979996669646431041 <<Base>>
  

  

  

   class C_0015376512757975965057 <<Base>>
  

  

  

  

  

   class C_0000794775527725307768 <<Base>>
  

  

  

  

   class C_0017487605234251182146 <<Element>>
  

  

   class C_0015644395940763327543 <<Element>>
  


'Generated with clang-uml, version 0.6.2
'LLVM version clang version 20.1.7 (https://github.com/llvm/llvm-project.git 6146a88f60492b520a36f8f8f3231e15f3cc6082)
@enduml
