@startuml
abstract "BaseArgument" as C_0014032639484775088103
abstract C_0014032639484775088103 {
#BaseArgument() = default : void
+~BaseArgument() constexpr = default : void
..
{abstract} +getValue() const = 0 : double
__
}
class "Vertex" as C_0002326256006988294087
class C_0002326256006988294087 {
+Vertex(float x, float y) : void
..
{static} +getLayout() : std::vector<Layout>
+x() const : float
+y() const : float
__
-x_ : float
-y_ : float
}
class "Vertex::Layout" as C_0002155889465830571527
class C_0002155889465830571527 {
__
+offset : void *
+size : int
}
class "SpaceVertex" as C_0013753387506434927655
class C_0013753387506434927655 {
+SpaceVertex(float x, float y, float distance) : void
..
+distance() const : float
{static} +getLayout() : std::vector<Layout>
__
-distance_ : float
}
class "SpaceRendererData" as C_0005127897508348657534
class C_0005127897508348657534 {
+SpaceRendererData() : void
+~SpaceRendererData() : void
..
-addLine(const Point & from, const Point & to, double distance) const : int
-addPoint(const Point & point) const : void
+arrowsRanges() const : std::vector<Range>
-extendLine(int lineIndex, const Point & point, double distance) const : void
+getPoints() const : std::vector<SpaceVertex>
+getVBO() const : std::vector<SpaceVertex>
+linesRanges() const : std::vector<Range>
+pointsRange() const : Range
__
-p : Private *
}
class "SpaceRendererData::Range" as C_0003956790280424976785
class C_0003956790280424976785 {
+operator+(const std::vector<SpaceVertex> & vertices) const : Range
__
+count : size_t
+from : size_t
}
class "Space" as C_0000228797310809486917
class C_0000228797310809486917 {
+Space(SpaceRendererData * rendererData) : void
+~Space() : void
..
+addPoint(const std::string & name, double x, double y) : void
+addPoint(const std::string & fromPointName, const std::string & name, double angle, double length) : void
+addPoint(const std::string & fromPointName, const std::string & name, Direction direction, double length) : void
-addPoint(const std::string & name, const Point & point) : void
+angle(const std::string & from, const std::string & to) const : double
+distance(const std::string & from, const std::string & to) const : double
+getPoint(const std::string & name) : Point &
+getRendererData() const : const SpaceRendererData *
+nextPoint(const std::string & name, double angle, double length) : void
+nextPoint(const std::string & name, Direction direction, double length) : void
__
-lastPointName_ : std::string
-linesIndices_ : std::unordered_map<std::string,int>
-parentPoints_ : std::unordered_map<std::string,std::string>
-points_ : std::unordered_map<std::string,Point>
-rendererData_ : SpaceRendererData *
}
enum "Space::Direction" as C_0006255543702469591148
enum C_0006255543702469591148 {
RIGHT
LEFT
UP
DOWN
}
class "PB::Dart" as C_0013418707691566027006
class C_0013418707691566027006 {
+Dart(Space * space) : void
..
+addPoint(const std::string & pointName) : void
+getPoints() : std::vector<float>
+getPolygon() : Polygon &
__
-polygon_ : Polygon
-space_ : Space *
}
class "PB::Outline" as C_0015223333465504068435
class C_0015223333465504068435 {
+Outline(Space * space) : void
+~Outline() : void
..
+addDart(Dart * dart) : void
+addPoint(const std::string & pointName) : void
+getPoints() const : std::vector<std::vector<float>>
+getShape() const : std::vector<float>
__
-darts_ : std::forward_list<Dart *>
-polygon_ : Polygon_with_holes
-space_ : Space *
}
class "PB::DartBuilder" as C_0002264357742943673553
class C_0002264357742943673553 {
+DartBuilder(Outline * outline, Dart * dart) : void
..
+addPoint(const std::string & pointName) : DartBuilder &
+complete() const : void
__
-dart_ : Dart *
-outline_ : Outline *
}
class "PB::OutlineBuilder" as C_0004467681112100964754
class C_0004467681112100964754 {
+OutlineBuilder(Outline * outline) : void
..
+addPoint(const std::string & pointName) : OutlineBuilder &
__
-outline_ : Outline *
}
class "PB::Pattern" as C_0005833888742069232503
class C_0005833888742069232503 {
+Pattern(const std::string & name, Space * space, Outline * outline) : void
..
+addPoint(const std::string & name, double x, double y) const : void
+addPoint(const std::string & from, const std::string & to, const BaseArgument * angle, const BaseArgument * length) const : void
+addPoint(const std::string & from, const std::string & to, Space::Direction direction, const BaseArgument * length) const : void
+editOutline() const : OutlineBuilder
+getOutline() const : std::vector<std::vector<float>>
+getShape() const : std::vector<float>
+nextPoint(const std::string & to, const BaseArgument * angle, const BaseArgument * length) const : void
+nextPoint(const std::string & to, Space::Direction direction, const BaseArgument * length) const : void
+sharePoint(const std::string & point, const Pattern * pattern) const : void
+startDart() const : DartBuilder
__
-name_ : std::string
-outline_ : Outline *
-space_ : Space *
}
class "PB::PatternBuilder" as C_0015340525554118583374
class C_0015340525554118583374 {
+PatternBuilder(Space * space, Pattern * pattern) : void
..
+addPoint(const std::string & name, double x, double y) : PatternBuilder &
+addPoint(const std::string & fromPointName, const std::string & name, double angle, double length) : PatternBuilder &
+addPoint(const std::string & fromPointName, const std::string & name, Space::Direction direction, double length) : PatternBuilder &
+editOutline() const : OutlineBuilder
+getSpace() const : Space &
+getSpaceRendererData() const : const SpaceRendererData *
+nextPoint(const std::string & name, double angle, double length) : PatternBuilder &
+nextPoint(const std::string & name, Space::Direction direction, double length) : PatternBuilder &
__
-pattern_ : Pattern *
-space_ : Space *
}
class "PB::Project" as C_0002059810468929738276
class C_0002059810468929738276 {
+Project(const std::string & name, ProjectParameters * parameters) : void
+~Project() : void
..
+addPattern(Pattern * pattern) : void
{static} +create() : Project *
+getName() : std::string
+getParameters() const : ProjectParameters *
-serialize<Archive>(Archive & archive, const unsigned int version) : void
+setName(const std::string & name) : void
__
-name_ : std::string
-parameters_ : ProjectParameters *
-patterns_ : std::forward_list<Pattern *>
}
class "Parameter" as C_0006906501909834539344
class C_0006906501909834539344 {
+Parameter(const std::string & name, double value) : void
..
+getName() const : const std::string &
+getValue() const : double
-serialize<Archive>(Archive & archive, const unsigned int version) : void
+setValue(double value) : void
__
-name_ : std::string
-value_ : double
}
class "ProjectParameters" as C_0015415048128036706046
class C_0015415048128036706046 {
+~ProjectParameters() : void
..
+addParameter(Parameter * parameter) : void
+count() const : unsigned int
+getParameter(const std::string & name) : Parameter *
-serialize<Archive>(Archive & archive, const unsigned int version) : void
__
-parameters_ : std::unordered_map<std::string,Parameter *>
}
class "Chrysalis::Pattern::Archive" as C_0013208927567080793949
class C_0013208927567080793949 {
+read(const char * filePath) : PB::Project *
+write(const char * filePath, PB::Project * project) : void
__
}
class "SpaceRendererData::Private" as C_0012658801633232851719
class C_0012658801633232851719 {
+addArrow(const Point & from, const Point & to) : void
__
+arrows_ : std::vector<std::vector<SpaceVertex>>
+lines_ : std::vector<std::vector<SpaceVertex>>
+points_ : std::vector<SpaceVertex>
}
class "Argument" as C_0017881155643566426614
class C_0017881155643566426614 {
+Argument(double value) : void
..
+getValue() const : double
__
-value_ : double
}
class "BinaryFunction" as C_0006214883631769309796
class C_0006214883631769309796 {
+BinaryFunction(BaseArgument * argumentLeft, BaseArgument * argumentRight, double (*)(double,double) function) : void
..
{static} +ADDITION(double a, double b) : double
{static} +DIVISION(double a, double b) : double
{static} +MAX(double a, double b) : double
{static} +MIN(double a, double b) : double
{static} +MULTIPLICATION(double a, double b) : double
{static} +SUBTRACTION(double a, double b) : double
+getValue() const : double
__
-argumentLeft : BaseArgument *
-argumentRight : BaseArgument *
-function : double (*)(double,double)
}
class "PatternRendererData" as C_0010500610705199261562
class C_0010500610705199261562 {
__
-vertices_ : std::vector<float>
}
class "VectorFunction" as C_0016617338678814122198
class C_0016617338678814122198 {
+VectorFunction(Space * space, const std::string & from, const std::string & to, double (*)(const VectorFunction *) function) : void
..
{static} +ANGLE(const VectorFunction * function) : double
{static} +LENGTH(const VectorFunction * function) : double
+getValue() const : double
__
-from : std::string
-function : double (*)(const VectorFunction *)
-space : Space *
-to : std::string
}
C_0002155889465830571527 --+ C_0002326256006988294087
C_0002326256006988294087 <|-- C_0013753387506434927655
C_0005127897508348657534 --> C_0012658801633232851719 : -p
C_0005127897508348657534 <.. C_0000228797310809486917 : +<<friend>>
C_0003956790280424976785 --+ C_0005127897508348657534
C_0000228797310809486917 --> C_0005127897508348657534 : -rendererData_
C_0006255543702469591148 --+ C_0000228797310809486917
C_0013418707691566027006 --> C_0000228797310809486917 : -space_
C_0015223333465504068435 --> C_0000228797310809486917 : -space_
C_0015223333465504068435 --> C_0013418707691566027006 : -darts_
C_0002264357742943673553 --> C_0013418707691566027006 : -dart_
C_0002264357742943673553 --> C_0015223333465504068435 : -outline_
C_0004467681112100964754 --> C_0015223333465504068435 : -outline_
C_0005833888742069232503 --> C_0000228797310809486917 : -space_
C_0005833888742069232503 --> C_0015223333465504068435 : -outline_
C_0015340525554118583374 --> C_0000228797310809486917 : -space_
C_0015340525554118583374 --> C_0005833888742069232503 : -pattern_
C_0002059810468929738276 --> C_0015415048128036706046 : -parameters_
C_0002059810468929738276 --> C_0005833888742069232503 : -patterns_
C_0014032639484775088103 <|-- C_0006906501909834539344
C_0015415048128036706046 --> C_0006906501909834539344 : -parameters_
C_0012658801633232851719 --+ C_0005127897508348657534
C_0012658801633232851719 o-- C_0013753387506434927655 : +points_
C_0012658801633232851719 o-- C_0013753387506434927655 : +arrows_
C_0012658801633232851719 o-- C_0013753387506434927655 : +lines_
C_0014032639484775088103 <|-- C_0017881155643566426614
C_0006214883631769309796 --> C_0014032639484775088103 : -argumentLeft
C_0006214883631769309796 --> C_0014032639484775088103 : -argumentRight
C_0014032639484775088103 <|-- C_0006214883631769309796
C_0016617338678814122198 --> C_0000228797310809486917 : -space
C_0014032639484775088103 <|-- C_0016617338678814122198
skinparam class {
  BackgroundColor #EAFAF1
  BorderColor #1E8449
  FontColor #0B5345
  AttributeFontColor #1E8449
  StereotypeFontColor #1E8449
  FontStyle Bold
}

skinparam class<<UI>> {
  BackgroundColor #F5EEF8
  BorderColor #8E44AD
  FontColor #4A235A
  AttributeFontColor #6C3483
  StereotypeFontColor #6C3483
}

skinparam class<<Builder>> {
  BackgroundColor #F2F3F4
  BorderColor #2C3E50
  BorderThickness 3
  FontSize 16
  FontColor #2C3E50
  AttributeFontColor #566573
  StereotypeFontColor #808B96
  FontStyle Italic
}


 

 

 

 

 

 

 

 class C_0013418707691566027006 <<PB>>  

 class C_0015223333465504068435 <<PB>>  

 class C_0002264357742943673553 <<PB>> <<Builder>> 

 class C_0004467681112100964754 <<PB>> <<Builder>> 

 class C_0005833888742069232503 <<PB>>  

 class C_0015340525554118583374 <<PB>> <<Builder>> 

 

 

 class C_0002059810468929738276 <<PB>>  

 class C_0013208927567080793949 <<Chrysalis::Pattern>>  

 

 

 

 

 

 


'Generated with clang-uml, version 0.6.2
'LLVM version clang version 20.1.7 (https://github.com/llvm/llvm-project.git 6146a88f60492b520a36f8f8f3231e15f3cc6082)
@enduml
